// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZd_VB5g4l0uU0B3Cu4Gm6qBPcjROclw',
    appId: '1:163024178822:web:f9e2663bfcf9047938cb07',
    messagingSenderId: '163024178822',
    projectId: 'estatelq',
    authDomain: 'estatelq.firebaseapp.com',
    storageBucket: 'estatelq.firebasestorage.app',
    measurementId: 'G-TN122YFSLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6FRPGSfm41Ztx1l4PonzMsOfPu9VM-7g',
    appId: '1:163024178822:android:06d9855d1cb49d4d38cb07',
    messagingSenderId: '163024178822',
    projectId: 'estatelq',
    storageBucket: 'estatelq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI1HjtQzPAx6Oym48sgfpITTr6IJCmLPs',
    appId: '1:163024178822:ios:fdd3360ec1dbdbf538cb07',
    messagingSenderId: '163024178822',
    projectId: 'estatelq',
    storageBucket: 'estatelq.firebasestorage.app',
    iosBundleId: 'com.example.estatelqapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI1HjtQzPAx6Oym48sgfpITTr6IJCmLPs',
    appId: '1:163024178822:ios:fdd3360ec1dbdbf538cb07',
    messagingSenderId: '163024178822',
    projectId: 'estatelq',
    storageBucket: 'estatelq.firebasestorage.app',
    iosBundleId: 'com.example.estatelqapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZd_VB5g4l0uU0B3Cu4Gm6qBPcjROclw',
    appId: '1:163024178822:web:13c71272ef278e3838cb07',
    messagingSenderId: '163024178822',
    projectId: 'estatelq',
    authDomain: 'estatelq.firebaseapp.com',
    storageBucket: 'estatelq.firebasestorage.app',
    measurementId: 'G-02WNST6W3D',
  );
}
