// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// FirebaseOptions for the Virtual Tour Firebase project.
///
/// This configuration is used to initialize the secondary
/// Firebase App for the propertyinspectorvirtualtour project.

class VirtualTourFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'VirtualTourFirebaseOptions have not been configured for Linux.',
        );

      default:
        throw UnsupportedError(
          'VirtualTourFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgEVEgCrduDg-NHSWBFSwcqs7sUmdeITA',
    appId: '1:921284994169:web:c103f36d5811112583e0a8',
    messagingSenderId: '921284994169',
    projectId: 'propertyinspectorvirtualtour',
    authDomain: 'propertyinspectorvirtualtour.firebaseapp.com',
    storageBucket: 'propertyinspectorvirtualtour.firebasestorage.app',
    measurementId: 'G-9JW041LNKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi5zoZl3YXMnJBqYBUUUUCIUtKKtRjGU0',
    appId: '1:921284994169:android:9f8b6606368ac93483e0a8',
    messagingSenderId: '921284994169',
    projectId: 'propertyinspectorvirtualtour',
    storageBucket: 'propertyinspectorvirtualtour.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCddwTHzCw-YXRo3CvMCERezTeC7NSP0kc',
    appId: '1:921284994169:ios:33e491ea07c3e6eb83e0a8',
    messagingSenderId: '921284994169',
    projectId: 'propertyinspectorvirtualtour',
    storageBucket: 'propertyinspectorvirtualtour.firebasestorage.app',
    iosBundleId: 'com.example.propertyInspector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCddwTHzCw-YXRo3CvMCERezTeC7NSP0kc',
    appId: '1:921284994169:ios:33e491ea07c3e6eb83e0a8',
    messagingSenderId: '921284994169',
    projectId: 'propertyinspectorvirtualtour',
    storageBucket: 'propertyinspectorvirtualtour.firebasestorage.app',
    iosBundleId: 'com.example.propertyInspector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgEVEgCrduDg-NHSWBFSwcqs7sUmdeITA',
    appId: '1:921284994169:web:d849f6657b79dc6083e0a8',
    messagingSenderId: '921284994169',
    projectId: 'propertyinspectorvirtualtour',
    authDomain: 'propertyinspectorvirtualtour.firebaseapp.com',
    storageBucket: 'propertyinspectorvirtualtour.firebasestorage.app',
    measurementId: 'G-E6FJV604J9',
  );
}
